add_library(
	t0_dssd
	dssd.cpp
)
target_include_directories(
	t0_dssd
	PUBLIC
	${PROJECT_SOURCE_DIR}
	${ROOT_INCLUDE_DIRS}
)
target_link_libraries(
	t0_dssd
	PUBLIC
	dssd_event
	dssd_match
	dssd_match_event
	ROOT::Core
	ROOT::RIO
	ROOT::Tree
)

add_library(
	t0_calibrate_utils
	calibrate_t0_utils.cpp
)
target_include_directories(
	t0_calibrate_utils
	PUBLIC
	${PROJECT_SOURCE_DIR}
	${ROOT_INCLUDE_DIRS}
)
target_link_libraries(
	t0_calibrate_utils
	PUBLIC
	config
	energy_calculator
	ROOT::Core
	ROOT::RIO
	ROOT::Hist
	ROOT::Graf
	ROOT::Gpad
)